//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterMarkService_Test.WatermarkingSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WatermarkingSvc.IWaterMarkService")]
    public interface IWaterMarkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaterMarkService/WaterMarkFile", ReplyAction="http://tempuri.org/IWaterMarkService/WaterMarkFileResponse")]
        byte[] WaterMarkFile(byte[] FileContents, string WaterMarkContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaterMarkService/WaterMarkFile", ReplyAction="http://tempuri.org/IWaterMarkService/WaterMarkFileResponse")]
        System.Threading.Tasks.Task<byte[]> WaterMarkFileAsync(byte[] FileContents, string WaterMarkContent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaterMarkServiceChannel : WaterMarkService_Test.WatermarkingSvc.IWaterMarkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaterMarkServiceClient : System.ServiceModel.ClientBase<WaterMarkService_Test.WatermarkingSvc.IWaterMarkService>, WaterMarkService_Test.WatermarkingSvc.IWaterMarkService {
        
        public WaterMarkServiceClient() {
        }
        
        public WaterMarkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaterMarkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterMarkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaterMarkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] WaterMarkFile(byte[] FileContents, string WaterMarkContent) {
            return base.Channel.WaterMarkFile(FileContents, WaterMarkContent);
        }
        
        public System.Threading.Tasks.Task<byte[]> WaterMarkFileAsync(byte[] FileContents, string WaterMarkContent) {
            return base.Channel.WaterMarkFileAsync(FileContents, WaterMarkContent);
        }
    }
}
